server:
  port: 9090
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
    
  h2:    console:      enabled: true
    
  jpa:
    database: h2
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
    
    
server.error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false

logging:
  level:
    org.springframework.web.client: DEBUG
    org.hibernate.type: TRACE
      
      